{"uuid": "322f16f7-8cd0-496f-a314-6f064d26b64f", "children": ["e0577fef-fa3b-4aba-aa21-bec027ae0831"], "befores": [{"name": "xunit_setup_method_fixture_TestLongin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"E:\\pytest_auto_uitest_apitest\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\pytest_auto_uitest_apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\pytest_auto_uitest_apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\pytest_auto_uitest_apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 841, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"E:\\pytest_auto_uitest_apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\pytest_auto_uitest_apitest\\demo.py\", line 15, in setup_method\n    self.driver = webdriver.Chrome()\n  File \"E:\\pytest_auto_uitest_apitest\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"E:\\pytest_auto_uitest_apitest\\venv\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 90, in __init__\n    self.service.start()\n  File \"E:\\pytest_auto_uitest_apitest\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1657357534416, "stop": 1657357534447}], "start": 1657357534416, "stop": 1657357534916}